spring:
  application:
    name: activity-service  # Required for config server to know which config to fetch
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888