spring:
  application:
    name: ai-service
  mongodb:
    uri: mongodb://localhost:27017/fitnessrecommendations
    database: fitnessrecommendations
  cloud:
    inetutils:
      preferred-networks:
        - 127.0
      ignored-interfaces:
        - eth.*
        - wlan.*

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: false
    instanceId: localhost:ai-service:8083
