spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/fitness-oauth2/protocol/openid-connect/certs
  cloud:
    inetutils:
      preferred-networks:
        - 127.0
      ignored-interfaces:
        - eth.*
        - wlan.*

server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: false
    instanceId: localhost:api-gateway:8080