server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-users-db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  cloud:
    inetutils:
      preferred-networks:
        - 127.0
      ignored-interfaces:
        - eth.*
        - wlan.*

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
    instanceId: localhost:user-service:8081
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

